---
language: ruby
cache: bundler
os: linux
dist: xenial
jobs:
  fast_finish: true
  include:
  - rvm: 2.4.10
  - rvm: 2.5.8
  - rvm: 2.6.6
  - rvm: 2.7.1
  - rvm: jruby-head
  - rvm: ruby-head
  - rvm: truffleruby
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head
  - rvm: truffleruby
before_install: gem install bundler
script:
- bundle exec rake rubocop
- bundle exec rake rspec
